import Head from 'next/head'
import { NextPage } from 'next';

const HomePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Home page</h1>
      <form>
        <div>
          <label htmlFor="email">Email</label>
          <input type="email" id="email"/>
        </div>
        <div>
          <label htmlFor="email">Your Feedback</label>
          <textarea rows={5}></textarea>
        </div>
        <button>Send Feedback</button>
      </form>
    </>
  )
}

export default HomePage;
